add back numba 0.48, presumably that has whatever cupy we need to avoid AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'