The testing is sensitive to the cupy version; with the wrong version, we can get AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'. The cupy version does not appear to be pinned and we might not want to, but this records the cupy version in the Travis build so that if we later have problems we can look at the last working build.